### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by glebec** [FullstackAcademy/fs-misc#1]
Apparently the shell script might not be Windows-compatible. Research and repair.

**Comment by glebec** [comment]
From the student who experienced this problem:

```
Error: spawn UNKNOWN
     at exports._errnoException (util.js:1022:11)
     at ChildProcess.spawn (internal/child_process.js:313:11)
     at exports.spawn (child_process.js:380:9)
     at Object.exports.execFile (child_process.js:143:15)
     at Promise (node_modules\fs-misc\lib\pg-init\index.js:21:18)
     at Object.createDb [as pgInit] (node_modules\fs-misc\lib\pg-init\index.js:20:10)
     at Context.<anonymous> (test\angular-check.js:13:21)
```

**Comment by glebec** [comment]
Culprit *might* be https://github.com/FullstackAcademy/fs-misc/blob/master/lib/pg-init/index.js#L13. Check `path.resolve` vs. `path.join`.
